default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: ENV["APPSTORECONNECT_API_KEY_ID"],
      issuer_id: ENV["APPSTORECONNECT_API_ISSUER_ID"],
      key_content: ENV["APPSTORECONNECT_API_KEY"]
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new beta build to Appstore"
  lane :prod do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: ENV["APPSTORECONNECT_API_KEY_ID"],
      issuer_id: ENV["APPSTORECONNECT_API_ISSUER_ID"],
      key_content: ENV["APPSTORECONNECT_API_KEY"]
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_app_store(
      force: true,
      automatic_release: false,
      submit_for_review: true,
      submission_information: { add_id_info_uses_idfa: false },
      precheck_include_in_app_purchases: false,
      skip_screenshots: true,
      reject_if_possible: true
    )
  end
end