default_platform(:android)

platform :android do
  desc "Beta (Internal Test)"
  lane :beta do
    sh "flutter build appbundle --release"
    upload_to_play_store(
      track: 'internal',
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Production Release"
  lane :release do
    sh "flutter build appbundle --release"
    upload_to_play_store(
      track: 'production',
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
