name: Shorebird Patch Android Beta

on:
  workflow_dispatch:

jobs:
  patch-android-beta:
    name: Shorebird Patch Android Beta
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Add Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/dimigoin-keystore.jks

      - name: Add Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" > android/key.properties

      - name: Add Google Service Json
        run: echo "${{ secrets.ANDROID_GOOGLE_SERVICE_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Add Firebase Options
        run: echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart

      - name: make env directory
        run: mkdir -p env

      - name: add .env file
        run: echo "${{ secrets.ENV }}" > env/.env

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install flutter sdk
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Read Flutter version
        run: echo "FLUTTER_VERSION=$(awk '$1 == \"flutter:\" { print $2; exit }' pubspec.yaml)" >> "$GITHUB_ENV"

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - run: flutter pub get

      - name: Read version from pubspec.yaml
        id: app_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Patch target version: $VERSION"

      - name: Create Shorebird Android patch
        run: shorebird patch android --flutter-version="$FLUTTER_VERSION" --release-version=${{ steps.app_version.outputs.version }}
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
